apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::068213564807:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HCPTAL5HY1G5
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::068213564807:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-02T18:24:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1628"
  uid: 4c56209f-ce4c-4b3a-8552-c91f867e1f2a
